### ISSUE TITLE
Upgrade frontend navigation

### ISSUE THREAD

**Issue by sebastiendeu** [NetaM-OSC/NetAM#55]
## idée
![image](https://user-images.githubusercontent.com/1666044/104312258-a735fd80-54d6-11eb-9000-e39d1c17ffee.png)

## Tasks
- [x] Use kaminari as pagination instead of datatable
- [x] Replace `Model.all` with `Model.accessible_by(current_ability)` when cancancan is configured
- [x] Use svg icons sprite
- [x] Replace admin-lte with native css 
- [x] Delete jQuery
- [ ] Implement [TypeSense](https://typesense.org) for search

## Guides
- Don't use jQuery, prefer native JavaScript
- Use Vue.js components when JavaScript is too complex
- Use Vue.js or partial when code is repeated
